/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * inputAnggota.java
 *
 * Created on Dec 11, 2010, 2:37:42 PM
 */

package com.masasdani.pemira.gui;

import com.masasdani.pemira.HibernateUtil;
import com.masasdani.pemira.dao.MahasiswaDao;
import com.masasdani.pemira.entity.Mahasiswa;
import com.masasdani.pemira.report.CetakLaporan;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author badak
 */
public class DataPemilih extends javax.swing.JPanel {

    List<Mahasiswa> list=new ArrayList<Mahasiswa>();
    private TableRowSorter sorter;
    MahasiswaDao mahasiswaDao;
    
    /** Creates new form inputAnggota */
    public DataPemilih() {
        initComponents();
        mahasiswaDao=HibernateUtil.getMahasiswaDao();
        list=mahasiswaDao.getAll();
        isiTabel();
        btnDelete.setEnabled(false);
        //btnPrint.setEnabled(false);
    }

    private void isiTabel(){    
        DefaultTableModel tabelmodel=new DefaultTableModel(new Object [][] {}, new String [] {"NIM", "Nama", "Jurusan"});
        for(Mahasiswa m : list){
            tabelmodel.addRow(new Object[] {m.getNim(), m.getNama(), m.getJurusan()});
        }
        tabelcari.setModel(tabelmodel);
        sorter=new TableRowSorter(tabelmodel);
        tabelcari.setRowSorter(sorter);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelcari = new javax.swing.JTable();
        filter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 36));
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daftar Pemilih");

        tabelcari.setAutoCreateRowSorter(true);
        tabelcari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelcari.setOpaque(false);
        tabelcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelcariMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelcari);

        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });
        filter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterKeyReleased(evt);
            }
        });

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Cari");

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnPrint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_filterActionPerformed

    private void filterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterKeyReleased
        // TODO add your handling code here:
        sorter.setRowFilter(javax.swing.RowFilter.regexFilter(filter.getText()));
    }//GEN-LAST:event_filterKeyReleased

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        CetakLaporan laporan = new CetakLaporan(list);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(tabelcari.getSelectedRow()!=-1){
            Mahasiswa m=new Mahasiswa();
            m.setNim(tabelcari.getValueAt(tabelcari.getSelectedRow(), 0).toString());
            m.setNama(tabelcari.getValueAt(tabelcari.getSelectedRow(), 1).toString());
            m.setJurusan(tabelcari.getValueAt(tabelcari.getSelectedRow(), 2).toString());
            mahasiswaDao.delete(m);
            btnDelete.setEnabled(false);
            list=mahasiswaDao.getAll();
            isiTabel();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tabelcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelcariMouseClicked
        // TODO add your handling code here:
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_tabelcariMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JTextField filter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelcari;
    // End of variables declaration//GEN-END:variables

}
