/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * inputAnggota.java
 *
 * Created on Dec 11, 2010, 2:45:56 PM
 */

package com.masasdani.pemira.gui;

import com.masasdani.pemira.HibernateUtil;
import com.masasdani.pemira.dao.MahasiswaDao;
import com.masasdani.pemira.entity.Mahasiswa;
import java.util.List;

/**
 *
 * @author badak
 */
public class InputMahasiswa extends javax.swing.JPanel {

    MahasiswaDao mahasiswaDao;
    /** Creates new form inputAnggota */
    public InputMahasiswa() {
        initComponents();
        cekked.setVisible(false);
        mahasiswaDao=HibernateUtil.getMahasiswaDao();
        clear();
        init();
    }

    private void simpan(){
        String nim=getNim();
        Mahasiswa m=new Mahasiswa();
        m.setNim(nim);
        m.setNama(nama.getText());
        m.setJurusan(jurusan.getText());
        m.setAngkatan(Integer.parseInt(angkatan.getText()));
        mahasiswaDao.save(m);
    }
    
    private boolean notExist(){
        boolean b=false;
        List<Mahasiswa> list=mahasiswaDao.getByNim(getNim());
        if(list.size()<1){
            b=true;
        }
        return b;
    }
    
    private void init(){
        nama.setEditable(false);
        btnSimpan.setEnabled(false);
    }

    private void clear(){
        nimJurusan.setText("");
        nimAngkatan.setText("");
        nimMahasiswa.setText("");
        nama.setText("");
        jurusan.setText("");
        angkatan.setText("");
    }
    
    private String getNim(){
        StringBuilder buffer= new StringBuilder();
        buffer.append(nimJurusan.getText());
        buffer.append(".");
        buffer.append(nimAngkatan.getText());
        buffer.append(".");
        buffer.append(nimMahasiswa.getText());
        return buffer.toString();
    }
    
    private boolean isKodeJurusan(){
        boolean validate=false;
        if(nimJurusan.getText().equals("a11")){
            validate=true;
            jurusan.setText("TI/S1");
        }
        if(nimJurusan.getText().equals("a21")){
            validate=true;
            jurusan.setText("TI/D3");
        }
        if(nimJurusan.getText().equals("a22")){
            validate=true;
            jurusan.setText("MI/D3");
        }
        if(nimJurusan.getText().equals("a23")){
            validate=true;
            jurusan.setText("KA/D3");
        }
        if(nimJurusan.getText().equals("a24")){
            validate=true;
            jurusan.setText("Broadcasting/D3");
        }
        if(nimJurusan.getText().equals("a12")){
            validate=true;
            jurusan.setText("SI");
        }
        if(nimJurusan.getText().equals("a14")){
            validate=true;
            jurusan.setText("DKV");
        }
        return validate;
    }
    
    private boolean isValidate(){
        boolean validate=false;
        if(isKodeJurusan()&&!nimAngkatan.getText().isEmpty()){
            angkatan.setText(nimAngkatan.getText());
            validate=true;
        }else{
            init();
        }
        return validate;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        nimJurusan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        angkatan = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        nimAngkatan = new javax.swing.JTextField();
        nimMahasiswa = new javax.swing.JTextField();
        jurusan = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        cekked = new javax.swing.JLabel();

        setOpaque(false);

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("NIM");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Angkatan");

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Jurusan");

        nama.setEditable(false);

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Nama");

        btnSimpan.setText("simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        nimJurusan.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Input Mahasiswa Pemilih");

        angkatan.setEditable(false);
        angkatan.setOpaque(false);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nimAngkatan.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nimMahasiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jurusan.setEditable(false);

        jButton3.setText("Periksa NIM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cekked.setText("cek");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nimJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nimAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nimMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cekked))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(angkatan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jurusan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                                .addComponent(nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nimJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nimAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nimMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(cekked))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(angkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(jButton2))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        simpan();
        clear();
        //this.dispose();
}//GEN-LAST:event_btnSimpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(isValidate()&&notExist()){
            cekked.setText("Nim Valid");
            cekked.setVisible(true);
            nama.setEditable(true);
            btnSimpan.setEnabled(true);
        }else{
            cekked.setText("Nim sudah masuk atau Tidak Valid");
            cekked.setVisible(true);
            init();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angkatan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel cekked;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jurusan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nimAngkatan;
    private javax.swing.JTextField nimJurusan;
    private javax.swing.JTextField nimMahasiswa;
    // End of variables declaration//GEN-END:variables

}
