/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panelUtama.java
 *
 * Created on Dec 12, 2010, 12:29:33 PM
 */

package com.masasdani.pemira.gui;

import com.masasdani.pemira.HibernateUtil;
import com.masasdani.pemira.dao.MahasiswaDao;
import javax.swing.JLabel;

/*import java.awt.BorderLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.doscom.openlibrary.connection.databaseUtilities;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;*/

/**
 *
 * @author badak
 */
public class PanelHome extends javax.swing.JPanel {

    //private JPanel panelchart;
    MahasiswaDao mahasiswaDao;
    String user;
    /** Creates new form panelUtama */
    public PanelHome() {
        initComponents();
        setSize(800, 400);
        mahasiswaDao=HibernateUtil.getMahasiswaDao();
        calculate();
        //panelchart.add(getChartPanel(), BorderLayout.NORTH);
    }

    public void setUser(String user) {
        this.user = user;
    }
    
    private void calculate(){
        labelTIs1.setText(""+mahasiswaDao.getByJurusan("TI/S1").size());
        labelSI.setText(""+mahasiswaDao.getByJurusan("SI").size());
        labelDKV.setText(""+mahasiswaDao.getByJurusan("DKV/S1").size());
        labelBroadcast.setText(""+mahasiswaDao.getByJurusan("Broadcast/D3").size());
        labelKA.setText(""+mahasiswaDao.getByJurusan("KA/D3").size());
        labelMi.setText(""+mahasiswaDao.getByJurusan("M1/D3").size());
        labelTId3.setText(""+mahasiswaDao.getByJurusan("TI/D3").size());
        labelTotal.setText(""+mahasiswaDao.getAll().size());
    }

     /*private PieDataset dataset(){
        DefaultPieDataset pieDataset=new DefaultPieDataset();
        try{
            Statement stm=databaseUtilities.getConnection().createStatement();
            ResultSet res=stm.executeQuery("select gender, count(gender) from anggota group by gender");
            while(res.next()){
                pieDataset.setValue(res.getString(1), res.getInt(2));
            }
        }catch(SQLException e){

        }
        return pieDataset;
    }

    private ChartPanel getChartPanel(){
        //Dataset d=dataset();
        JFreeChart genderChart=ChartFactory.createPieChart3D("gender", dataset(), true, true, false);
        ChartPanel cp=new ChartPanel(genderChart);
        cp.setSize(300, 200);
        cp.setOpaque(false);
        return cp;
    }*/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelAbout = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelTIs1 = new javax.swing.JLabel();
        labelSI = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelMi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelKA = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelTId3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelBroadcast = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelDKV = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(799, 454));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 36));
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEMIRA UDINUS");

        panelAbout.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Hasil data pemungut suara");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("TI /S1");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("SI/S1");

        labelTIs1.setFont(new java.awt.Font("Ubuntu", 1, 24));
        labelTIs1.setForeground(java.awt.Color.white);
        labelTIs1.setText("Value");

        labelSI.setFont(new java.awt.Font("Ubuntu", 1, 24));
        labelSI.setForeground(java.awt.Color.white);
        labelSI.setText("Value");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("MI/D3");

        labelMi.setFont(new java.awt.Font("Ubuntu", 1, 24));
        labelMi.setForeground(java.awt.Color.white);
        labelMi.setText("Value");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("KA/D3");

        labelKA.setFont(new java.awt.Font("Ubuntu", 1, 24));
        labelKA.setForeground(java.awt.Color.white);
        labelKA.setText("Value");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("TI/D3");

        labelTId3.setFont(new java.awt.Font("Ubuntu", 1, 24));
        labelTId3.setForeground(java.awt.Color.white);
        labelTId3.setText("Value");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Broadcast/D3");

        labelBroadcast.setFont(new java.awt.Font("Ubuntu", 1, 24));
        labelBroadcast.setForeground(java.awt.Color.white);
        labelBroadcast.setText("Value");

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("DKV/S1");

        labelDKV.setFont(new java.awt.Font("Ubuntu", 1, 24));
        labelDKV.setForeground(java.awt.Color.white);
        labelDKV.setText("Value");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Total");

        labelTotal.setFont(new java.awt.Font("Ubuntu", 1, 24));
        labelTotal.setForeground(java.awt.Color.white);
        labelTotal.setText("Value");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTIs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelKA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTId3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelBroadcast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDKV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTIs1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSI)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMi)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelKA)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTId3)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBroadcast)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDKV)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotal)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBroadcast;
    private javax.swing.JLabel labelDKV;
    private javax.swing.JLabel labelKA;
    private javax.swing.JLabel labelMi;
    private javax.swing.JLabel labelSI;
    private javax.swing.JLabel labelTId3;
    private javax.swing.JLabel labelTIs1;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel panelAbout;
    // End of variables declaration//GEN-END:variables

}
